iris
attach(iris)
library(dplyr)
select(iris,Sepal.Length)
select(iris,sepala=Sepal.Length)
rename(iris,sepala=Sepal.Length)
mutate(iris,nova=Petal.Length - Petal.Width)
transmute(iris,Petal.Length,Petal.Width,Petal.Length - Petal.Width)
detach(iris)
teste<-group_by(iris,Species)
summarise(teste,sum(Sepal.Length))
summarise(teste,Sepal.Length=n())
a<-5
select(iris,5)
vars<-c("Sepal.Length","Sepal.Width")
select(iris,vars,Petal.Length)
select(iris,a,identity(a))
